### ISSUE TITLE
Sendgrid API Oauth authenication not working

### ISSUE THREAD

**Issue by MohammedMubeen** [sendgrid/csharp-http-client#102]
Hi Folks , 

Please share me sample c# code for oauth validation for webhook

Please help me

Send grid , I have map my own client id and secret , please find the sample screen shot.

C#:
  HttpResponseMessage response = new HttpResponseMessage();
            //var header = Request.Headers.Authorization.ToString();
            //string token = header.Replace("Bearer ", "");
            //bool IsValid = ValidateToken(token);
            //if (IsValid)

**Comment by thinkingserious** [comment]
Hello @MohammedMubeen,

I believe you may be referring to [this documentation](https://github.com/sendgrid/sendgrid-csharp/blob/bb5337f7f8ac63906178bea823cb781758f3a009/tests/SendGrid.Tests/Helpers/EventWebhook/RequestValidatorTests.cs).

With best regards,

Elmer

**Comment by MohammedMubeen** [comment]
Hi @thinkingserious ,

Thanks for the replay.

I go through the documents you referred.

I expected, through api using postman, how to set header "Bearer".

If hitting api, facing authorization failed error?

NOTE : Without oauth api hitting, its working fine

**Comment by JenniferMah** [comment]
Hi @MohammedMubeen 
Can you provide the error log you are receiving when authorization has failed?
