### ISSUE TITLE
New HttpClient for each new request

### ISSUE THREAD

**Issue by nillis** [sendgrid/csharp-http-client#17]
#### Issue Summary

Is there a specific reason why a new HttpClient is instantiated on each request which is made through this client?

Reusing a HttpClient instance is considered a best practice regarding to performance and memory pressure. I'm glad to do a pull request, but first wanted to verify there isn't a specific reason to not reuse the instance.
f.e. https://skimming.net/why-you-should-reuse-httpclient-instances/

![image](https://cloud.githubusercontent.com/assets/2675228/20536372/0e3a8294-b0e9-11e6-8ee0-c29819b4a46b.png)

**Comment by thinkingserious** [comment]
No reason.

A pull request would be greatly appreciated :)

**Comment by chriskallen** [comment]
Is this going to be merged in anytime soon?

**Comment by thinkingserious** [comment]
Hi @chriskallen,

I'm not sure, we are awaiting a signed CLA from @nillis.

I noticed we have the [same issue in our new v9 SDK](https://github.com/sendgrid/sendgrid-csharp/issues/405), so I've created a ticket for that. I would appreciate you vote on that issue to help it move up the queue. Thanks!

**Comment by nillis** [comment]
I submitted my CLA so my PR can be merged :)

**Comment by thinkingserious** [comment]
This issue was solved here: https://github.com/sendgrid/csharp-http-client/issues/18

Thanks!
