### ISSUE TITLE
Make requests cancellable

### ISSUE THREAD

**Issue by aKzenT** [sendgrid/csharp-http-client#21]
HttpClient allows cancellation via CancellationToken. Using this API it is currently not possible to pass a cancellation token. Therefore you cannot cancel long running requests.

It would be helpful in our scenario to be able to cancel running requests. CancellationToken provides a standard way to do this and it should be easy to include this as an extra parameter. Please consider it for an upcoming release.

Thanks!

**Comment by aKzenT** [comment]
I added the necessary code in the referenced pull request. Kindly review.

**Comment by thinkingserious** [comment]
Hello @aKzenT,

Checking the pull request now ...

Note that the v9beta branch of our official library will have this functionality included: https://github.com/sendgrid/sendgrid-csharp/blob/single-email/src/SendGrid/SendGridClient.cs#L254. That beta should be available no later then early next month with any luck.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Closed with https://github.com/sendgrid/csharp-http-client/pull/22
