### ISSUE TITLE
Access forbidden

### ISSUE THREAD

**Issue by mastan** [sendgrid/csharp-http-client#4]
#### Issue Summary

Access forbidden error with Visual Studio 2013-Full working code from https://github.com/sendgrid/csharp-http-client/blob/master/Example/Example.cs 
#### Steps to Reproduce

![forbidden](https://cloud.githubusercontent.com/assets/3243228/15360973/58188672-1d2d-11e6-8d9f-c8e01a112e52.jpg)
![envrionmentvariable](https://cloud.githubusercontent.com/assets/3243228/15360974/581d1732-1d2d-11e6-8107-6b95231f2701.jpg)
1. Downloaded source from https://github.com/sendgrid/csharp-http-client/blob/master/Example/Example.cs
2. Changed Environment Variable in local box
3. Executed the project

Console shows an error as attached.
#### Technical details:
- csharp-http-client Version: master (latest commit: [commit number])
- CSharp Version: 4.5

**Comment by thinkingserious** [comment]
Hello @mastan,

It looks like you are using our API Key ID, your API key should start with "SG." and should be about three times the size of what you have above.

Note that when you create a new API Key, the full key is only displayed once for your security. If you need to create a new key, you can do so here: https://app.sendgrid.com/settings/api_keys

Also, if you want to use a library to access SendGrid's API, then please take a look at our official library here: https://github.com/sendgrid/sendgrid-csharp (please note the beta message at the top, as we have a major update right around the corner). This library is meant to be a general purpose library for any API.

Thanks!

With Best Regards,

Elmer
