### ISSUE TITLE
How to fix Mono errors during Travis CI build?

### ISSUE THREAD

**Issue by mbernier** [sendgrid/csharp-http-client#51]
#### Issue Summary

We are seeing 
```
The command "mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe UnitTest/bin/Release/UnitTest.dll -domain:None" exited with 3.
```
On every build. Can you help with this?

**Comment by phongphan** [comment]
It's likely a bug in corefx [#59302](https://bugzilla.xamarin.com/show_bug.cgi?id=59302)

**Comment by mbernier** [comment]
@phongphan I noticed that the same error happened after a huge stack trace, after #56 #57 failures. I am wondering if there is something wrong with the way that the unittests are asserting issues and reporting them out to the log? or is mono failing totally normal when a unittest doesn't pass?

Here's where I saw those issues: https://travis-ci.org/sendgrid/csharp-http-client/builds/294260033?utm_source=github_status&utm_medium=notification

**Comment by mbernier** [comment]
@adlan are the csharp unittest errors always so verbose / disorganized? I noticed the same error and stacktracing was happening [here](https://travis-ci.org/sendgrid/csharp-http-client/builds/294337852?utm_source=github_status&utm_medium=notification) (the build from #53)

**Comment by phongphan** [comment]
Even if I commented out the test in #53. Both of them are still failing under mono. Not sure what exactly triggered the failure though.

**Comment by adlan** [comment]
@mbernier, uncaught exceptions will be displayed verbosely. In this case those exceptions are not what the unittest runner expected.

For the remaining exceptions, I can only guess (based on the commit log) that the cause of failing has todo with the test environment and is likely as what @phongphan mentioned earlier. I've yet to dig those errors deeply though.
