### ISSUE TITLE
Create a Use Cases Directory

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/csharp-http-client#61]
Due to the success we have seen from hacktoberfest, we are seeing more people create use cases. This is amazing! 
We want to make sure that everyone can find them. Please help us to break up this file and make it easier to read and manage:
- Create a Use Cases Directory
- Put a README.md in this directory
- Make a file in the new directory for each individual Use Case from USE_CASES.md, copy the content to this file
- For each file you've created, link to it from the README you created
- Organize the links in the README by type
- Make sure the names of the files you created are related to the Use Case
Thank you!

**Comment by ed-parry** [comment]
Hi @thinkingserious - is this still an active issue? Happy to take a look but couldn't find a starting file in the project?

**Comment by thinkingserious** [comment]
Thanks @ed-parry!

Here is an example [empty use case file](https://github.com/sendgrid/python-http-client/blob/master/USE_CASES.md).

And [here is how the directory](https://github.com/sendgrid/sendgrid-python/tree/master/use_cases) should look.

**Comment by ed-parry** [comment]
@thinkingserious Thanks for that - so are there no current use cases for this project at the moment - it's mostly just setup? I think I was expecting to find the full `USE_CASES.md` file but if that's a different project I guess it'll just be setup for now for future use cases to be added?

**Comment by ed-parry** [comment]
@thinkingserious I've gone ahead with a PR to create the directory and README and link to them from the main README as I had some free time. If this matches what you were after at this stage then we're all good, otherwise let me know and I'll happily revise :)
