### ISSUE TITLE
Datasource

### ISSUE THREAD

**Issue by mendizalea** [sendgrid/csharp-http-client#64]
Hello,

I can see the response from restful api for example in messagebox but a do not know have tu bing in datagridview.

How I can do it?

Thanks

**Comment by thinkingserious** [comment]
Hello @mendizalea,

This is not an issue related to this open source library. I suggest that you seek references about the `DataGridView` such as [this one](https://www.dotnetperls.com/datagridview).

Best of luck!

With Best Regards,

Elmer
