### ISSUE TITLE
Client replaces single quotes with double quotes in request payload 

### ISSUE THREAD

**Issue by gliljas** [sendgrid/csharp-http-client#7]
https://github.com/sendgrid/csharp-http-client/blob/master/CSharpHTTPClient/Client.cs#L311

Here, the client replaces single quotes with double quotes. That is unexpected behavior.

Single quotes are perfectly valid inside JSON string tokens.
# https://github.com/sendgrid/sendgrid-csharp/issues/256

**Comment by thinkingserious** [comment]
Please shoot us an email at dx@sendgrid.com with your T-shirt size and mailing address so we can send you some swag. Your help with identifying the issue quickly is greatly appreciated!
