### ISSUE TITLE
HTTP Timeout Parameter

### ISSUE THREAD

**Issue by PandaBoy00** [sendgrid/csharp-http-client#8]
It isn't a bug per se but more of a feature.  It would be nice to be able to add a parameter for the HTTP timeout so we can adjust to our needs.

**Comment by mribichich** [comment]
+1

**Comment by thinkingserious** [comment]
Thanks for the +1 @mribichich! That helps move this up the prioritization queue.

**Comment by thinkingserious** [comment]
Solved by: https://github.com/sendgrid/csharp-http-client/pull/23

**Comment by PandaBoy00** [comment]
Enhancement done by #23
