### ISSUE TITLE
Proxy question

### ISSUE THREAD

**Issue by dbeattie71** [sendgrid/csharp-http-client#91]
`Client` has a private field, `_httpClient` which seems to only be used if `BuildHttpClient` is called which I don't  see called anywhere.

Is `BuildHttpClient` supposed to be called?

Thanks.

**Comment by thinkingserious** [comment]
Hello @dbeattie71,

Thanks for the heads up and my apologies for the confusion. I have removed the unused function and the associated variable.

With best regards,

Elmer
