### ISSUE TITLE
How can I send email without using the aysnc method?

### ISSUE THREAD

**Issue by warrenkc** [sendgrid/csharp-http-client#92]
#### Issue Summary

ASP.net webforms project.

#### Steps to Reproduce

1. I want to send email using the C# client.
2. var response = await client.SendEmailAsync(msg);
3. How can I send the email message without it being async? 

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* csharp-http-client Version: master (latest commit: [commit number])
* CSharp Version: 4.5

**Comment by thinkingserious** [comment]
Hello @warrenkc,

Please replace `Execute().Wait();` with `Execute().Result();` in [this example](https://github.com/sendgrid/csharp-http-client/blob/master/Example/Example.cs).

With best regards,

Elmer
